function radarParameters = importRadarParameters(fileName)
% Read the CSV file into a table
dataTable = readtable(fileName);

% Initialize an empty struct to hold radar parameters
radarParameters = struct();

% Loop through each row of the table and populate the struct
for i = 1:height(dataTable)
    % Extract the radar name from the 'Field' column
    radarName = dataTable.Field{i};

    % Assign the corresponding fields to the radar struct
    radarParameters.(radarName) = struct(...
        'TOA', dataTable.TOA(i), ...
        'AOA', dataTable.AOA(i), ...
        'peakAmp', dataTable.peakAmp(i), ...
        'Freq', dataTable.Freq(i), ...
        'PRI', dataTable.PRI(i), ...
        'PW', dataTable.PW(i), ...
        'scanMode', string(dataTable.scanMode{i}), ...
        'scanPeriod', dataTable.scanPeriod(i), ...
        'Beamwidth', dataTable.Beamwidth(i));
end
end